apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: efk
  namespace: efk
spec:
  chart:
    spec:
      version: ">=3.0.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: efk.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
